// Le stringhe DINAMICHE di bordo (i18n fetta 1): ciò che ui.js e main.js
// compongono a runtime — HUD, Cantiere, diario, gilde, alleanze, morte,
// toast e rosa dei venti. Generato dagli script di conversione a t().

import { addDict } from './i18n.js';

const it = {
  "alleanza.accetta": "🤝 Accetta",
  "alleanza.ammaina": "🏳 Ammaina la bandiera aperta",
  "alleanza.bandiera.riga": "Alleanza di {nomi} — {n} {posti}",
  "alleanza.declina": "Declina",
  "alleanza.giadentro": "Sei già in un'alleanza: prima sciogli le vele",
  "alleanza.invita": "✉ Invita",
  "alleanza.invita.aria": "Invita {nome} nell'alleanza",
  "alleanza.issa": "🏴 Issa la bandiera aperta",
  "alleanza.lascia.aria": "Lascia l'alleanza",
  "alleanza.mia": "🤝 La tua alleanza ({n}/{max})",
  "alleanza.nessuno": "Nessun altro capitano in queste acque, per ora.",
  "alleanza.nonrisponde": "Nessun capitano risponde a «{f}».",
  "alleanza.piena": "L'alleanza è al completo",
  "alleanza.posti": "posti",
  "alleanza.posto": "posto",
  "alleanza.propone": "{nome} ti propone un'alleanza",
  "alleanza.sciogli": "🌊 Sciogli le vele",
  "alleanza.tu": " — tu",
  "alleanza.unisciti": "🤝 Unisciti",
  "alleanza.unisciti.aria": "Unisciti all'alleanza di {nomi}",
  "armi.altre": "✦ Le altre abilità: {lista} — ognuna viene col suo scafo, la scheda Varo le spiega tutte.",
  "armi.cambiavaro": "⚓ Cambia al Varo",
  "armi.cambiavaro.aria": "Apri la scheda Varo: le abilità si cambiano varando un altro tipo di nave",
  "armi.giatua": "→ {nome} · già tua",
  "armi.indietro": "⇄ {nome} · gratis",
  "armi.indietro.aria": "Rimonta {a} al posto di {da}: gratis, l'esclusiva resta nel tuo arsenale",
  "armi.indietro.title": "Il ripensamento è gratis: l'esclusiva resta tua, il Mortaio torna al livello massimo",
  "armi.nota": "⚫ In mare ogni bocca spara la munizione scelta col tasto X: palle piene (danno pieno), catene (tagliano le vele), mitraglia (falcidia la ciurma). Il colpo in poppa morde ×1.5. Le esclusive comprate restano nel tuo arsenale: col ⇄ torni al Mortaio e viceversa, gratis.",
  "armi.nuovoslot": "+ Nuovo slot (con colubrina) · {costo} 🪙",
  "armi.potenzia": "Potenzia · {costo} 🪙",
  "armi.potenzia.aria": "Potenzia {nome} ({gruppo}) per {costo} monete",
  "armi.r.mia": "<div class=\"shopInfo\"><b>✦ La tua abilità — tasto R: {emo} {nome}</b><span>Effetto MOMENTANEO: {effetto} Poi si ricarica ({cd}s: la barra R sotto le fiancate).</span><span class=\"effetti\">L'abilità viaggia col TIPO di nave ({tipo}), non coi cannoni: per averne un'altra devi varare un altro tipo.</span></div>",
  "armi.r.nessuna": "<div class=\"shopInfo\"><b>✦ Abilità R: non ne hai ancora una</b><span>L'abilità speciale (tasto R) viene col TIPO di nave: scegline uno al Varo e la trovi a bordo.</span></div>",
  "armi.rimonta.aria": "Rimonta {nome}{stats}: è nel tuo arsenale, gratis",
  "armi.slotcount": "{n}/{max} slot",
  "armi.sostituisci": "→ {nome} · {costo} 🪙",
  "armi.sostituisci.aria": "Sostituisci {da} con {a}{stats} per {costo} monete",
  "armi.stats": "{dmg} danni · gittata {range} · ricarica {reload}s",
  "armi.stats.brevi": "{dmg} danni, gittata {range}, ricarica {reload}s",
  "armi.suprema": "Arma suprema",
  "armi.tier": "Tier {r}",
  "assedio.countdown": "⚔ Assedio a {t}: si salpa tra {s}s!",
  "assedio.lobby": "⚔ Assedio a {t}: in cerca di sfidanti…",
  "assedio.nessuno": "Nessun assedio in corso. Banditene uno: scegli il tuo ruolo!",
  "assedio.running": "⚔ ASSEDIO IN CORSO su {t} — {s}s",
  "azione.massimo": "Massimo",
  "bandiera.sel.aria": "{label} della bandiera",
  "board.testata": "<tr><th scope=\"col\">Corsaro</th><th scope=\"col\">Affondate</th><th scope=\"col\">Perdute</th><th scope=\"col\">Monete 🪙</th></tr>",
  "consiglio.completo": "👑 La nave è al completo: da qui in poi si fa la leggenda.",
  "consiglio.consiglia": "⭐ Il mastro d'ascia consiglia: {cosa} · {costo} 🪙 ",
  "consiglio.passa": "passare a {arma} ({gruppo})",
  "consiglio.portamici": "Portamici",
  "consiglio.potenzia": "potenziare la {arma} ({gruppo})",
  "consiglio.punto": "un punto {nome}",
  "consiglio.riempi": "🪙 Riempi il forziere: il primo acquisto utile è {cosa} a {costo} 🪙 (ne hai {oro}).",
  "consiglio.slot": "uno slot in più ({gruppo})",
  "consiglio.vai.aria": "Vai a {cosa}",
  "costo.mancano": "Servono {costo} 🪙 — ne hai {oro}",
  "diario.assalta": "Assalta le difese di {b}",
  "diario.campagna": "⚔ Campagna della settimana: «{nome}»",
  "diario.compiuta": "⭐ Compiuta! (+{p} 🪙)",
  "diario.dungeon": "🗺 Dungeon del giorno: «{nome}»",
  "diario.espugna": "Espugna una Fortezza Proibita",
  "diario.giorni": "giorni",
  "diario.giorno": "giorno",
  "diario.incassati": "+{r} 🪙 incassati",
  "diario.incorso": "In corso",
  "diario.mie": "Le mie",
  "diario.premio": "Premio del Mastro: {p} 🪙",
  "diario.rinnovo": "⏳ Le rotte si rinnovano tra {h}h {m}m",
  "diario.settimana": "📅 Settimana piena: {n}/7 giorni col tris — a 7/7 valgono +{p} 🪙",
  "diario.tredelgiorno": "Le tre del giorno",
  "diario.tris": "Il tris del giorno",
  "diario.tris.compi": "🌟 Compi tutte e tre e incassi +{v} 🪙 (tris {p} + strike ×{x})",
  "diario.tris.fatto": "✓ Tris del giorno incassato",
  "diario.tris.tutte": "🌟 Tutte e tre compiute: +{v} 🪙 (strike di {n} {giorni})",
  "diario.tutte": "Tutto il mare",
  "diario.vuoto.mastro": "Nessuna impresa del Mastro in corso.",
  "diario.vuoto.mie": "Nessuna tua impresa, per ora. Salpa e falle parlare!",
  "diario.vuoto.rotte": "Le rotte del giorno arrivano col mare: salpa e torna a leggere.",
  "diario.vuoto.tutte": "Il mare è quieto: nessuna notizia.",
  "gilda.ammetti": "⛵ Ammetti",
  "gilda.aperte": "porte aperte",
  "gilda.chiedi": "⚔ Chiedi l'ingresso",
  "gilda.chiedi.title": "Hai conquistato il diritto: la richiesta parte subito",
  "gilda.chiuse": "porte chiuse",
  "gilda.ciurma": "⚓ La ciurma ({n}/24)",
  "gilda.fonda.costo": "🏴 Fonda la Fratellanza ({costo} 🪙)",
  "gilda.lasciala": "🌊 Lascia la Fratellanza",
  "gilda.log": "📖 Il log della Fratellanza",
  "gilda.nessuna": "Nessuna Fratellanza batte ancora bandiera: la prima potrebbe essere la tua.",
  "gilda.promuovi": "⭐ Promuovi",
  "gilda.richieste": "✉ Richieste in rada",
  "gilda.rifiuta": "Rifiuta",
  "gilda.rito.prima": "⚔ Prima il rito",
  "gilda.rito.title": "Blocca una loro nave per conquistare il diritto (vale 7 giorni)",
  "gilda.sbarcalo": "Sbarca",
  "gilda.sciogli": "🌊 Sciogli la Fratellanza",
  "gilda.sciogli.conferma": "🌊 Sicuro? Premi di nuovo per sciogliere",
  "gilda.tag.aperta": "aperta",
  "gilda.tag.chiusa": "chiusa",
  "gruppo.bow": "▲ Prua ({k})",
  "gruppo.left": "◀ Fiancata sinistra ({k})",
  "gruppo.right": "▶ Fiancata destra ({k})",
  "gruppo.stern": "▼ Poppa ({k})",
  "livree.anteprima": "anteprima della nave…",
  "livree.compra": "Compra · {costo} 🪙",
  "livree.compra.aria": "Compra {nome} per {costo} monete",
  "livree.guadagna": "Si guadagna",
  "livree.guadagna.title": "Compi la campagna del Mastro di Rotte per guadagnarla",
  "livree.indossa": "Indossa",
  "livree.indossa.aria": "Indossa {nome}",
  "livree.nota": "🎨 Il Negozio delle Livree — solo estetica, mai vantaggio.",
  "livree.riponi": "Riponi",
  "livree.riponi.aria": "Riponi {nome}",
  "livree.salpa": "Salpa per vedere la livrea in mare.",
  "livree.sez.livrea": "🎨 Livree",
  "livree.sez.livrea.desc": "l'abito completo: scafo, finiture e tela",
  "livree.sez.scia": "🌊 Scie",
  "livree.sez.scia.desc": "la strada che lasci sul mare",
  "livree.sez.vele": "⛵ Vele",
  "livree.sez.vele.desc": "solo la tela, sopra qualunque livrea",
  "map.verso.aria": "Mappa del tesoro: rotta tracciata verso {nome}",
  "morte.abissi": " Il forziere è rimasto a bordo: gli abissi non fanno bottino.",
  "morte.consiglio": "Ogni punto di Stiva mette al riparo un 10% in più del forziere.",
  "morte.da": "Affondato da {chi}.",
  "morte.mare": "Il mare si è preso la tua nave.",
  "morte.perso": " Il forziere in gioco è passato al vincitore: −{p} 🪙",
  "morte.salvo": " — il doppiofondo della Stiva ne ha salvati {s}.",
  "nave.ciurma": "Ciurma",
  "nave.ciurma.desc": "Più braccia, bordate più fitte",
  "nave.scafo": "Scafo",
  "nave.scafo.desc": "Legno di quercia, ossa dure",
  "nave.stiva": "Stiva",
  "nave.stiva.desc": "Un doppiofondo che i vincitori non trovano",
  "nave.timone": "Timone",
  "nave.timone.desc": "Vira come un pesce, non come un tronco",
  "nave.vele": "Vele",
  "nave.vele.desc": "Chi fugge vive per combattere domani",
  "nome.portofranco": "Porto Franco",
  "reg.addosso": "(addosso)",
  "reg.altre": "…e altre {n}",
  "reg.approdi": "⭐ Approdi preferiti",
  "reg.approdi.vuoto": "Il mare è grande: segna i porti che ami",
  "reg.arsenale": "⚔ L'arsenale a bordo",
  "reg.arsenale.vuoto": "Nessuna bocca da fuoco (come ci sei arrivato fin qui?)",
  "reg.battaglie": "Battaglie: <b>{v}</b> vittorie · {n} naufragi",
  "reg.concampagna": "si guadagna con la campagna",
  "reg.fortezze": "🏰 Fortezze espugnate",
  "reg.fortezze.vuoto": "Ancora nessuna: le mura aspettano le tue bordate",
  "reg.guardaroba": "🎨 Il guardaroba ({n}/{tot})",
  "reg.mastro": "⚔ Il Mastro di Rotte",
  "reg.mastro.compiuta": "Campagna della settimana: <b>compiuta</b>",
  "reg.nave": "⛵ La nave",
  "reg.negozio.vuoto": "Il Negozio delle Livree apre al Porto Franco",
  "reg.senzavaro": "Nessun varo ancora: il Cantiere aspetta",
  "reg.tipo": "Tipo: <b>{nome}</b> ({n} vari all'attivo)",
  "shop.nave.banner": "⚓ La tua nave: <b>{nome}</b> — {sotto}",
  "sito.attraccato": "⚓ Attraccato: {nome}",
  "sito.pref.on": "★ Approdo preferito",
  "statrow.compra.aria": "Compra un punto {cosa} per {costo} monete",
  "statrow.livello.aria": "livello {lvl} di {max}",
  "tempo.adesso": "adesso",
  "tempo.giorni": "{n} giorni fa",
  "tempo.ieri": "ieri",
  "tempo.min": "{n} min fa",
  "tempo.ore": "{n} ore fa",
  "tempo.unora": "un'ora fa",
  "timoneria.premi": "premi un tasto…",
  "timoneria.tasto.aria": "Tasto per {nome}: ora {label}. Attiva e premi il nuovo tasto (ESC annulla)",
  "tipo.galeone": "Galeone",
  "tipo.goletta": "Goletta",
  "tipo.guerra": "Brigantino da Guerra",
  "tipo.sciabecco": "Sciabecco",
  "toast.abilitavaro": "✦ L'abilità arriva col varo: Cantiere del Porto Franco (tasto F)",
  "toast.ancorata": "⚓ Ancora gettata: il bottino è al sicuro in mare aperto.",
  "toast.bentornato": "⚓ Bentornato a bordo, capitano.",
  "toast.connessione": "⚠ Il mare si è chiuso: connessione perduta. Ricarica per salpare di nuovo.",
  "toast.dungeon": "⚔ Il Mastro ha steso un dungeon qui: abbatti le difese per il bottino!",
  "toast.espugnata": "🏰 FORTEZZA ESPUGNATA! Il blocco è caduto per te, per sempre.",
  "toast.falcidiata": "☠ Ciurma falcidiata: si ricarica piano!",
  "toast.fortezza": "⚠ Quelle acque sono difese da una Fortezza quasi inespugnabile!",
  "toast.nuovarotta": "🧭 Nuova rotta richiesta: si salpa!",
  "toast.portofranco": "⚓ Attracca al Porto Franco (tasto F) per il Cantiere e la Bacheca degli Assedi",
  "toast.preferiti8": "⭐ Hai già 8 approdi preferiti: togline uno prima",
  "toast.riparata": "Nave riparata a nuovo. Il mare ti aspetta.",
  "toast.scriviancora": "Scrivi il nome del tuo ancoraggio, poi il codice.",
  "toast.tastoriservato": "Quel tasto serve alla navigazione: scegline un altro.",
  "toast.veletagliate": "⛓ Vele tagliate: la nave arranca!",
  "varo.abilita.riga": "✦ <b>R — {nome}</b> (ricarica {cd}s): {effetto}",
  "varo.eff.scafo": "scafo {pct}",
  "varo.eff.sconto": "{linea} a metà prezzo",
  "varo.eff.velocita": "velocità {pct}",
  "varo.eff.virata": "virata {pct}",
  "varo.esclusiva.riga": "☄ esclusiva: <b>{nome}</b>",
  "varo.nota.cambia": "⚓ Cambiare identità costa {costo} 🪙 (raddoppia a ogni giro). Le esclusive comprate restano tue.",
  "varo.nota.primo": "⚓ Scegli il tipo della tua nave: il primo varo costa {costo} 🪙.",
  "varo.riga.breve": "abilità: {abilita} · esclusiva: {esclusiva}",
  "varo.tuanave": "La tua nave",
  "varo.vara": "Vara · {costo} 🪙",
  "varo.vara.aria": "Vara {nome} per {costo} monete",
  "vento.aria": "Vento da {p}, {forza}",
  "vento.brezza": "brezza",
  "vento.burrasca": "burrasca",
  "vento.nome": "da {p} · {forza}",
  "vento.punte": "E,SE,S,SO,O,NO,N,NE",
  "vento.punte.aria": "est,sud-est,sud,sud-ovest,ovest,nord-ovest,nord,nord-est",
  "vento.tempesta.aria": "Sei in una burrasca: vento pieno da {p}, gittata ridotta",
  "vento.tempesta.nome": "⛈ burrasca! · da {p}",
  "vento.tempesta.title": "Burrasca! Il vento morde a forza piena e le palle volano corte: esci dalla pioggia o approfittane",
  "vento.teso": "vento teso",
  "vento.title": "Il vento tira da {p} ({forza}); la freccia indica dove spinge: in poppa corri, di bolina freni",
  "vessillo.ammaina": "Ammaina",
  "vessillo.ammaina.aria": "Ammaina il vessillo personale",
  "vessillo.anteprima.aria": "Anteprima del vessillo",
  "vessillo.cambia": "Cambia il vessillo",
  "vessillo.head": "<b>🚩 Il tuo vessillo</b><span>gratis — la gilda, se ce l'hai, vince</span>",
  "vessillo.issa": "Issa il vessillo",
  "vessillo.sel.aria": "{label} del vessillo",
};

const en = {
  "alleanza.accetta": "🤝 Accept",
  "alleanza.ammaina": "🏳 Strike the open flag",
  "alleanza.bandiera.riga": "Alliance of {nomi} — {n} {posti}",
  "alleanza.declina": "Decline",
  "alleanza.giadentro": "You are already in an alliance: loose the sails first",
  "alleanza.invita": "✉ Invite",
  "alleanza.invita.aria": "Invite {nome} into the alliance",
  "alleanza.issa": "🏴 Hoist the open flag",
  "alleanza.lascia.aria": "Leave the alliance",
  "alleanza.mia": "🤝 Your alliance ({n}/{max})",
  "alleanza.nessuno": "No other captains in these waters, for now.",
  "alleanza.nonrisponde": "No captain answers to «{f}».",
  "alleanza.piena": "The alliance is full",
  "alleanza.posti": "seats",
  "alleanza.posto": "seat",
  "alleanza.propone": "{nome} proposes an alliance",
  "alleanza.sciogli": "🌊 Loose the sails",
  "alleanza.tu": " — you",
  "alleanza.unisciti": "🤝 Join",
  "alleanza.unisciti.aria": "Join the alliance of {nomi}",
  "armi.altre": "✦ The other abilities: {lista} — each comes with its hull; the Launch tab explains them all.",
  "armi.cambiavaro": "⚓ Change at Launch",
  "armi.cambiavaro.aria": "Open the Launch tab: abilities change by launching a different ship type",
  "armi.giatua": "→ {nome} · already yours",
  "armi.indietro": "⇄ {nome} · free",
  "armi.indietro.aria": "Remount {a} in place of {da}: free, the exclusive stays in your arsenal",
  "armi.indietro.title": "Changing your mind is free: the exclusive stays yours, the Mortar returns at max level",
  "armi.nota": "⚫ At sea every gun fires the ammunition chosen with the X key: round shot (full damage), chains (cut the sails), grapeshot (scythes the crew). A stern hit bites ×1.5. Purchased exclusives stay in your arsenal: with ⇄ you go back to the Mortar and vice versa, free.",
  "armi.nuovoslot": "+ New slot (with culverin) · {costo} 🪙",
  "armi.potenzia": "Upgrade · {costo} 🪙",
  "armi.potenzia.aria": "Upgrade {nome} ({gruppo}) for {costo} coins",
  "armi.r.mia": "<div class=\"shopInfo\"><b>✦ Your ability — key R: {emo} {nome}</b><span>MOMENTARY effect: {effetto} Then it recharges ({cd}s: the R bar under the broadsides).</span><span class=\"effetti\">The ability travels with your ship TYPE ({tipo}), not with the guns: for a different one you must launch a different type.</span></div>",
  "armi.r.nessuna": "<div class=\"shopInfo\"><b>✦ Ability R: you don't have one yet</b><span>The special ability (key R) comes with your ship TYPE: pick one at the Launch tab and you'll find it aboard.</span></div>",
  "armi.rimonta.aria": "Remount {nome}{stats}: it is in your arsenal, free",
  "armi.slotcount": "{n}/{max} slots",
  "armi.sostituisci": "→ {nome} · {costo} 🪙",
  "armi.sostituisci.aria": "Replace {da} with {a}{stats} for {costo} coins",
  "armi.stats": "{dmg} damage · range {range} · reload {reload}s",
  "armi.stats.brevi": "{dmg} damage, range {range}, reload {reload}s",
  "armi.suprema": "Supreme weapon",
  "armi.tier": "Tier {r}",
  "assedio.countdown": "⚔ Siege of {t}: sailing in {s}s!",
  "assedio.lobby": "⚔ Siege of {t}: looking for challengers…",
  "assedio.nessuno": "No siege under way. Call one: choose your role!",
  "assedio.running": "⚔ SIEGE UNDER WAY on {t} — {s}s",
  "azione.massimo": "Maxed",
  "bandiera.sel.aria": "Flag {label}",
  "board.testata": "<tr><th scope=\"col\">Corsair</th><th scope=\"col\">Sunk</th><th scope=\"col\">Lost</th><th scope=\"col\">Coins 🪙</th></tr>",
  "consiglio.completo": "👑 The ship is complete: from here on you build the legend.",
  "consiglio.consiglia": "⭐ The shipwright recommends: {cosa} · {costo} 🪙 ",
  "consiglio.passa": "switching to {arma} ({gruppo})",
  "consiglio.portamici": "Take me there",
  "consiglio.potenzia": "upgrading the {arma} ({gruppo})",
  "consiglio.punto": "one {nome} point",
  "consiglio.riempi": "🪙 Fill the chest: the first useful purchase is {cosa} at {costo} 🪙 (you have {oro}).",
  "consiglio.slot": "one more slot ({gruppo})",
  "consiglio.vai.aria": "Go to {cosa}",
  "costo.mancano": "You need {costo} 🪙 — you have {oro}",
  "diario.assalta": "Assault the defences of {b}",
  "diario.campagna": "⚔ Campaign of the week: «{nome}»",
  "diario.compiuta": "⭐ Completed! (+{p} 🪙)",
  "diario.dungeon": "🗺 Dungeon of the day: «{nome}»",
  "diario.espugna": "Storm a Forbidden Fortress",
  "diario.giorni": "day",
  "diario.giorno": "day",
  "diario.incassati": "+{r} 🪙 collected",
  "diario.incorso": "Under way",
  "diario.mie": "Mine",
  "diario.premio": "Pathmaster's prize: {p} 🪙",
  "diario.rinnovo": "⏳ Routes renew in {h}h {m}m",
  "diario.settimana": "📅 Full week: {n}/7 days with the treble — at 7/7 it pays +{p} 🪙",
  "diario.tredelgiorno": "Today's three",
  "diario.tris": "The daily treble",
  "diario.tris.compi": "🌟 Complete all three and collect +{v} 🪙 (treble {p} + streak ×{x})",
  "diario.tris.fatto": "✓ Daily treble collected",
  "diario.tris.tutte": "🌟 All three done: +{v} 🪙 ({n}-{giorni} streak)",
  "diario.tutte": "The whole sea",
  "diario.vuoto.mastro": "No Pathmaster feat under way.",
  "diario.vuoto.mie": "No feats of yours yet. Set sail and make them talk!",
  "diario.vuoto.rotte": "The routes of the day come with the sea: set sail and come back to read.",
  "diario.vuoto.tutte": "The sea is quiet: no news.",
  "gilda.ammetti": "⛵ Admit",
  "gilda.aperte": "open doors",
  "gilda.chiedi": "⚔ Ask for admission",
  "gilda.chiedi.title": "You earned the right: the request goes out at once",
  "gilda.chiuse": "closed doors",
  "gilda.ciurma": "⚓ The crew ({n}/24)",
  "gilda.fonda.costo": "🏴 Found the Brotherhood ({costo} 🪙)",
  "gilda.lasciala": "🌊 Leave the Brotherhood",
  "gilda.log": "📖 The Brotherhood log",
  "gilda.nessuna": "No Brotherhood flies its flag yet: the first could be yours.",
  "gilda.promuovi": "⭐ Promote",
  "gilda.richieste": "✉ Requests in the roadstead",
  "gilda.rifiuta": "Refuse",
  "gilda.rito.prima": "⚔ The rite first",
  "gilda.rito.title": "Disable one of their ships to earn the right (lasts 7 days)",
  "gilda.sbarcalo": "Put ashore",
  "gilda.sciogli": "🌊 Dissolve the Brotherhood",
  "gilda.sciogli.conferma": "🌊 Sure? Press again to dissolve",
  "gilda.tag.aperta": "open",
  "gilda.tag.chiusa": "closed",
  "gruppo.bow": "▲ Bow ({k})",
  "gruppo.left": "◀ Port broadside ({k})",
  "gruppo.right": "▶ Starboard broadside ({k})",
  "gruppo.stern": "▼ Stern ({k})",
  "livree.anteprima": "ship preview…",
  "livree.compra": "Buy · {costo} 🪙",
  "livree.compra.aria": "Buy {nome} for {costo} coins",
  "livree.guadagna": "Earned only",
  "livree.guadagna.title": "Complete the Pathmaster's campaign to earn it",
  "livree.indossa": "Wear",
  "livree.indossa.aria": "Wear {nome}",
  "livree.nota": "🎨 The Livery Shop — looks only, never an advantage.",
  "livree.riponi": "Put away",
  "livree.riponi.aria": "Put away {nome}",
  "livree.salpa": "Set sail to see the livery at sea.",
  "livree.sez.livrea": "🎨 Liveries",
  "livree.sez.livrea.desc": "the full dress: hull, trim and canvas",
  "livree.sez.scia": "🌊 Wakes",
  "livree.sez.scia.desc": "the road you leave on the sea",
  "livree.sez.vele": "⛵ Sails",
  "livree.sez.vele.desc": "canvas only, over any livery",
  "map.verso.aria": "Treasure map: course charted to {nome}",
  "morte.abissi": " The chest stayed aboard: the abyss takes no loot.",
  "morte.consiglio": "Every Hold point shelters an extra 10% of the chest.",
  "morte.da": "Sunk by {chi}.",
  "morte.mare": "The sea has taken your ship.",
  "morte.perso": " The chest in play went to the victor: −{p} 🪙",
  "morte.salvo": " — the Hold's false bottom saved {s} of it.",
  "nave.ciurma": "Crew",
  "nave.ciurma.desc": "More arms, thicker broadsides",
  "nave.scafo": "Hull",
  "nave.scafo.desc": "Oak timber, hard bones",
  "nave.stiva": "Hold",
  "nave.stiva.desc": "A false bottom the victors never find",
  "nave.timone": "Helm",
  "nave.timone.desc": "Turns like a fish, not like a log",
  "nave.vele": "Sails",
  "nave.vele.desc": "He who flees lives to fight tomorrow",
  "nome.portofranco": "Free Port",
  "reg.addosso": "(worn)",
  "reg.altre": "…and {n} more",
  "reg.approdi": "⭐ Favourite moorings",
  "reg.approdi.vuoto": "The sea is wide: mark the ports you love",
  "reg.arsenale": "⚔ The arsenal aboard",
  "reg.arsenale.vuoto": "No guns at all (how did you even get here?)",
  "reg.battaglie": "Battles: <b>{v}</b> victories · {n} shipwrecks",
  "reg.concampagna": "earned with the campaign",
  "reg.fortezze": "🏰 Fortresses stormed",
  "reg.fortezze.vuoto": "None yet: the walls await your broadsides",
  "reg.guardaroba": "🎨 The wardrobe ({n}/{tot})",
  "reg.mastro": "⚔ The Pathmaster",
  "reg.mastro.compiuta": "Weekly campaign: <b>completed</b>",
  "reg.nave": "⛵ The ship",
  "reg.negozio.vuoto": "The Livery Shop opens at Free Port",
  "reg.senzavaro": "No launch yet: the Shipyard awaits",
  "reg.tipo": "Type: <b>{nome}</b> ({n} launches so far)",
  "shop.nave.banner": "⚓ Your ship: <b>{nome}</b> — {sotto}",
  "sito.attraccato": "⚓ Docked: {nome}",
  "sito.pref.on": "★ Favourite mooring",
  "statrow.compra.aria": "Buy one {cosa} point for {costo} coins",
  "statrow.livello.aria": "level {lvl} of {max}",
  "tempo.adesso": "just now",
  "tempo.giorni": "{n} days ago",
  "tempo.ieri": "yesterday",
  "tempo.min": "{n} min ago",
  "tempo.ore": "{n} hours ago",
  "tempo.unora": "an hour ago",
  "timoneria.premi": "press a key…",
  "timoneria.tasto.aria": "Key for {nome}: now {label}. Activate and press the new key (ESC cancels)",
  "tipo.galeone": "Galleon",
  "tipo.goletta": "Schooner",
  "tipo.guerra": "War Brigantine",
  "tipo.sciabecco": "Xebec",
  "toast.abilitavaro": "✦ The ability comes with the launch: Free Port Shipyard (key F)",
  "toast.ancorata": "⚓ Anchor dropped: your loot is safe on the open sea.",
  "toast.bentornato": "⚓ Welcome back aboard, captain.",
  "toast.connessione": "⚠ The sea has closed: connection lost. Reload to set sail again.",
  "toast.dungeon": "⚔ The Pathmaster laid a dungeon here: bring down the defences for the loot!",
  "toast.espugnata": "🏰 FORTRESS STORMED! The blockade has fallen for you, forever.",
  "toast.falcidiata": "☠ Crew scythed: reloading is slow!",
  "toast.fortezza": "⚠ Those waters are guarded by a near-impregnable Fortress!",
  "toast.nuovarotta": "🧭 New course requested: setting sail!",
  "toast.portofranco": "⚓ Dock at Free Port (key F) for the Shipyard and the Siege Board",
  "toast.preferiti8": "⭐ You already have 8 favourite moorings: remove one first",
  "toast.riparata": "Ship repaired good as new. The sea awaits.",
  "toast.scriviancora": "Type your anchorage name, then the code.",
  "toast.tastoriservato": "That key is needed for navigation: pick another.",
  "toast.veletagliate": "⛓ Sails cut: the ship limps!",
  "varo.abilita.riga": "✦ <b>R — {nome}</b> (recharge {cd}s): {effetto}",
  "varo.eff.scafo": "hull {pct}",
  "varo.eff.sconto": "{linea} at half price",
  "varo.eff.velocita": "speed {pct}",
  "varo.eff.virata": "turn {pct}",
  "varo.esclusiva.riga": "☄ exclusive: <b>{nome}</b>",
  "varo.nota.cambia": "⚓ Changing identity costs {costo} 🪙 (doubles each time). Purchased exclusives remain yours.",
  "varo.nota.primo": "⚓ Choose your ship type: the first launch costs {costo} 🪙.",
  "varo.riga.breve": "ability: {abilita} · exclusive: {esclusiva}",
  "varo.tuanave": "Your ship",
  "varo.vara": "Launch · {costo} 🪙",
  "varo.vara.aria": "Launch {nome} for {costo} coins",
  "vento.aria": "Wind from {p}, {forza}",
  "vento.brezza": "breeze",
  "vento.burrasca": "gale",
  "vento.nome": "from {p} · {forza}",
  "vento.punte": "E,SE,S,SW,W,NW,N,NE",
  "vento.punte.aria": "east,south-east,south,south-west,west,north-west,north,north-east",
  "vento.tempesta.aria": "You are in a squall: full wind from {p}, reduced range",
  "vento.tempesta.nome": "⛈ squall! · from {p}",
  "vento.tempesta.title": "Squall! The wind bites at full force and shot flies short: get out of the rain or make it count",
  "vento.teso": "stiff wind",
  "vento.title": "The wind blows from {p} ({forza}); the arrow shows where it pushes: downwind you run, close-hauled you slow",
  "vessillo.ammaina": "Strike it",
  "vessillo.ammaina.aria": "Strike your personal ensign",
  "vessillo.anteprima.aria": "Ensign preview",
  "vessillo.cambia": "Change the ensign",
  "vessillo.head": "<b>🚩 Your ensign</b><span>free — the guild flag, if you have one, wins</span>",
  "vessillo.issa": "Hoist the ensign",
  "vessillo.sel.aria": "Ensign {label}",
};

addDict(it, en);
